[package]
name = "efs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
blake3 = "1.3"
hex = "0.4"
object_store = { version = "0.11", features = ["aws"] }
bptree = { git = "https://github.com/Dan-J-D/bptree" }
zeroize = { version = "1.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"
